function [Br,Bz,Atheta] = bfield_circular_coil_analytic(a,d,r,z)
%
% Calculates the magnetic field components generated by a filamentary current
% loop. It is assumed that the loop is in a plane perpendicular to the z axis
% and is centered on the z axis. All units taken to be MKS (Amperes, meters,
% Tesla). Uses the Matlab function ellipke to calculate the complete elliptic
% integrals of the first and second kind K and E.
%
% Input parameters: 
% 
%  a   radius of current loop 
%  d   axial distance of loop from z=0 point ( can be >0 or <0 ) 
%  r   radius at which B components are calculated 
%  z   axial location at which B components are calculated
%
% Output parameters:
% Br   radial B component
% Bz   axial B component
% Atheta  azimuthal vector potential
%
% J.D. Lore modified from Goulding

mu0_4pi = 1.e-7;

Br = zeros(size(r));
Bz = zeros(size(r));
if nargout > 2
    Atheta = zeros(size(r));
end

% The standard elliptic-integral form is singular on axis even though the
% physical field is finite there, so treat r = 0 using the analytic limit.
is_axis = (r == 0);
is_off_axis = ~is_axis;

if any(is_axis(:))
    dz0 = z(is_axis) - d;
    Bz(is_axis) = 2*pi*mu0_4pi*a.^2 ./ (a.^2 + dz0.^2).^(3/2);
end

if any(is_off_axis(:))
    ro = r(is_off_axis);
    zo = z(is_off_axis);

    m = 4*ro.*a ./ ((ro+a).^2 + (zo-d).^2);
    sm = sqrt(m);
    [K,E] = ellipke(m);

    sa = sqrt(a);
    sroa = sqrt(ro./a);
    dz = zo - d;
    m1 = m - 1;

    Br(is_off_axis) = -2*mu0_4pi./ro.^(1.5).*dz./sa.*(sm/2.*K - sm/4.*(m-2)./m1.*E);

    Bz(is_off_axis) = 2*mu0_4pi./ro.*(sroa.*sm/2.*K - sm./(4*m1).*(sroa.*(m-2) + m./sroa).*E);

    if nargout > 2
        Atheta(is_off_axis) = 2*mu0_4pi./sroa .*((2./sm - sm).*K - 2./sm.*E);
    end
end
