function [Athetag]=afield_circular_coil_analytic(a,d,r,z)
% Calculates the magnetic field components generated by a filamentary current
% loop. It is assumed that the loop is in a plane perpendicular to the z axis
% and is centered on the z axis. All units taken to be MKS (Amperes, meters,
% Tesla). Uses the Matlab function ellipke to calculate the complete elliptic
% integrals of the first and second kind K and E.

% Input parameters: 
% 
%  a   radius of current loop 
%  d   axial distance of loop from z=0 point ( can be >0 or <0 ) 
%  I   current in loop  
%  r   radius at which B components are calculated 
%  z   axial location at which B components are calculated

% Output parameters:
% Atheta  azimuthal vector potential
% J.D Lore modified from Goulding
u2=4*r.*a./((r+a).^2+(z-d).^2);  % argument of elliptical integral functions
u=sqrt(u2);
[K,E]=ellipke(u2);
sroa = sqrt(r./a);
Athetag=2e-7./sroa.*((2./u-u).*K-2./u.*E);
Athetag(r<eps) = 0;