function area = pappus(R1,Z1,R2,Z2)
% area = pappus(R,Z)
% or
% area = pappus(R1,Z1,R2,Z2)
% This function calculates the surface area generated by rotating a line segment
% around the z-axis using Pappus's centroid theorem.
% JDL 

if nargin == 4
    area = pappus1(R1,Z1,R2,Z2);
else
    R = R1;
    Z = Z1;
    n = length(R); % Number of sides

    % Check if closed
    if R(1) == R(n) && Z(1) == Z(n)
        n = n - 1; % Reduce the count as the loop is already closed
    else
        % Add the first vertex at the end to complete the loop
        R(end+1) = R(1);
        Z(end+1) = Z(1);
    end

    area = 0;
    for i = 1:n
        area = area + pappus1(R(i),Z(i),R(i+1),Z(i+1));
    end
end

end


function area1 = pappus1(R1,Z1,R2,Z2)
    area1 = 2*pi*sqrt( (R2 - R1)^2 + (Z2 - Z1)^2 )*mean([R1,R2]);
end